### ISSUE TITLE
shutdown issue in Ventura

### ISSUE THREAD

**Issue by occparty** [fahis1/DELL-latitude-7390-hackintosh-monterey#1]
hey fahis1, I have a latitude 7390 too but with a touchscreen, and I built an EFI from scratch with Dortania's Guide.
My problem is that I can not turn off 7390 with normal step: when I click shutdown, the notebook restarts instead. So I try your whole EFI except my USBport.kext; it can boot into Ventura 13.2.1 smoothly but still it returns restart when I shutdown.

Do you encounter the same problem? Or can you give me some advice?
Thank you!

I've tried https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html and acpi guide in 
https://github.com/5T33Z0/OC-Little-Translated

**Comment by halal-beef** [comment]
you need to disable the touchscreen in ur uefi settings or else u will kpanic

**Comment by halal-beef** [comment]
you can use updated voodooi2c and voodooi2chid but you will lose ur trackpad multitouch gestures
